- hosts: Galaxy
  remote_user: root
  vars_files:
    - ./vars/galaxy.yml
    - ./vars/params.yml
  pre_tasks:
    - name: create galaxy user
      user: name=galaxy state=present system=yes home="{{galaxy_home}}" uid="{{galaxy_user_uid}}" shell=/bin/bash
    - name: Install package with semanage command
      yum: name="policycoreutils-python" state=present
    - name: Allow httpd to network connect
      command: /usr/sbin/setsebool -P httpd_can_network_connect 1
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - name: Label galaxy-dist file directory for httpd usage
      command: semanage fcontext -a -t httpd_sys_content_t "{{galaxy_server_selinux}}"
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - name: Label galaxy home for httpd usage
      command: semanage fcontext -a -t httpd_sys_content_t "{{galaxy_home}}"
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - name: Restore selinux information
      command: restorecon -R -v "{{galaxy_home}}"
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - name: Change galaxy home to allow apache group RH
      file: path="{{galaxy_home}}" owner=galaxy group=apache mode=0750
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - name: Change galaxy home to allow apache group Other
      file: path="{{galaxy_home}}" owner=galaxy group=www-data mode=0750
      when: ansible_distribution != 'RedHat' and ansible_distribution != 'CentOS'

    - name: Update bash_profile for "{{galaxy_user}}"
      lineinfile:
        dest="{{galaxy_home}}/.bash_profile"
        line="export PATH=${HOME}/bin:${PATH}"
        regexp="export PATH=\${HOME}\/bin:\${PATH}"
        owner=galaxy
        state=present
        insertafter=EOF
        create=True
    - name: download python2.x
      get_url: dest='/tmp/python.tgz' url='https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz'
      sudo: yes
      sudo_user: "{{galaxy_user}}"
    - name: upack python2.x
      command: chdir=/tmp tar xzvf python.tgz
      sudo: yes
      sudo_user: "{{galaxy_user}}"
    - name: configure python2.x
      command: chdir=/tmp/Python-2.7.10 ./configure --prefix="{{galaxy_home}}"
      sudo: yes
      sudo_user: "{{galaxy_user}}"
    - name: compile python2.x
      command: chdir=/tmp/Python-2.7.10 make
      sudo: yes
      sudo_user: "{{galaxy_user}}"
    - name: install python2.x
      command: chdir=/tmp/Python-2.7.10 make install
      sudo: yes
      sudo_user: "{{galaxy_user}}"

    - name: getpip
      get_url: dest='/tmp/get-pip.py' url='https://bootstrap.pypa.io/get-pip.py'
      sudo: yes
      sudo_user: "{{galaxy_user}}"
    - name: install pip
      command: chdir="/tmp/" python get-pip.py
      sudo: yes
      sudo_user: "{{galaxy_user}}"
    - name: install virtualenv
      command: pip install virtualenv
      sudo: yes
      sudo_user: "{{galaxy_user}}"

  roles:
    - role: galaxyprojectdotorg.galaxy
      sudo: yes
      sudo_user: "{{galaxy_user}}"
  post_tasks:
    - name: configure contrib script for where galaxy is located
      replace: dest="{{galaxy_server_dir}}/contrib/galaxy.fedora-init" regexp="/path/to/galaxy-dist" replace="{{galaxy_server_dir}}"
    - name: copy RH init script to init.d
      command: cp "{{galaxy_server_dir}}/contrib/galaxy.fedora-init" /etc/init.d/galaxy
    - name: make galaxy script executable
      command: chmod 755 /etc/init.d/galaxy
    - name: set galaxy to start on boot
      command: chdir=/etc/init.d /sbin/chkconfig galaxy on
    - name: install CAS logout page into static directory
      template: src=./templates/logout.php.j2 dest="{{logout_page_location}}"
    - name: Verifies that {{apache_error_dir}} exists
      file: path={{apache_error_dir}} state=directory
    - name: install Custom 401 Page
      template: src=./templates/401.html.j2 dest="{{page_location_401}}"
    - name: Restore selinux information once more
      command: restorecon -R -v "{{galaxy_home}}"
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'