---
# defaults file for galaxyprojectdotorg.galaxy
# MUST NOT END WITH A /
galaxy_server_dir: "{{galaxy_home}}/galaxy-dist"

# Controls which tasks are included, in case you need to perform different
# options on different hosts or server directories.
galaxy_manage_clone: yes
galaxy_vcs: git

# changed to our fork of the galaxy repo.. just in case we do customizations
#galaxy_git_repo: https://github.com/galaxyproject/galaxy.git
galaxy_git_repo: https://github.com/UH-CI/galaxy

# Download the Galaxy instead cloning, for throw away boxes (e.g. Docker)
galaxy_manage_download: no
galaxy_manage_static_setup: yes
galaxy_manage_mutable_setup: yes
galaxy_manage_database: yes
galaxy_fetch_eggs: yes

# This can be a tag (as shown here) but doing so will cause the revision check
# task to always report "changed"
galaxy_changeset_id: "master"
galaxy_config_dir: "{{ galaxy_server_dir }}/config"

SHARED_HOME: "/lus/scratch/galaxy/"

galaxy_logdir: "{{galaxy_home}}/logs/"
galaxy_piddir: "{{galaxy_home}}/pids/"


galaxy_config:
  "server:main":
    host: 127.0.0.1
    use_threadpool: true
    use: "egg:Paste#http"

  "server:handler0":
    host: 127.0.0.1
    use: "egg:Paste#http"
    port: 8090
    use_threadpool: true
    threadpool_workers: 5

  "server:handler1":
    host: 127.0.0.1
    use: "egg:Paste#http"
    port: 8091
    use_threadpool: true
    threadpool_workers: 5

  "uwsgi":
    processes: 4
    stats: 127.0.0.1:9191
    socket: 127.0.0.1:4001
    http: 127.0.0.1:4002
    pythonpath: lib
    threads: 4
    logto: "{{galaxy_logdir}}/uwsgi.log"
    pidfile: "{{galaxy_piddir}}/uwsgi.pid"
    master: True
    
  "app:main":
    static_enabled:  False
    debug: False
    expose_dataset_path: False
    normalize_remote_user_email: True
# CHANGE/SET ME BEFORE DEPLOY
    remote_user_secret: 111 
# CHANGE/SET ME BEFORE DEPLOY
    id_secret: 111
    database_engine_option_server_side_cursors: True
    cleanup_job: always
    log_level: INFO
    
    database_connection: "postgresql:///galaxy"
    user_activation_on: "False"
    use_remote_user: "True"
    remote_user_maildomain: "hawaii.edu"
    remote_user_logout_href: "{{CAS_LOGOUT}}"
    admin_users: "SET ME!"
    require_login: "True"
    allow_user_creation: "False"
    allow_user_dataset_purge: "True"
    enable_quotas: "True"
    new_user_dataset_access_role_default_private: "True"
    job_config_file: "{{galaxy_config_dir}}/job_conf.xml"
    outputs_to_working_directory: "False"
    cleanup_job: "always"
    environment_setup_file: "{{galaxy_home}}/.bash_profile"
    tool_config_file: "{{galaxy_config_dir}}/shed_tool_conf.xml,{{galaxy_config_dir}}/tool_conf.xml.sample"

    tool_dependency_dir: "{{SHARED_HOME}}tool_dependency"
    apache_xsendfile: "True"
    upstream_gzip: "True"
    ftp_upload_dir: "{{SHARED_HOME}}users/"
    ftp_upload_site:
    
    new_file_path: "{{SHARED_HOME}}datastore/tmp"
    file_path: "{{SHARED_HOME}}datastore/datasets"
    openid_consumer_cache_path: "{{SHARED_HOME}}datastore/openid_consumer_cache"
    citation_cache_data_dir: "{{SHARED_HOME}}datastore/citations/data"
    citation_cache_lock_dir: "{{SHARED_HOME}}datastore/citations/locks"
    whoosh_index_dir: "{{SHARED_HOME}}datastore/whoosh_cache"
    template_cache_path: "{{SHARED_HOME}}datastore/template_cache"
    object_store_cache_path: "{{SHARED_HOME}}datastore/object_store_cache"
    job_working_directory: "{{SHARED_HOME}}datastore/jobs"

  loggers:
    keys: root,main,handler0,handler1
  handlers:
    keys: file,console
  formatters:
    keys: generic
  logger_root:
    level: INFO
    handlers: file

  logger_main:
    level: INFO
    handlers: file
    qualname: galaxy
    propagate: 0
  logger_handler0:
    level: INFO
    handlers: file
    qualname: galaxy
    propagate: 0
  logger_handler1:
    level: INFO
    handlers: file
    qualname: galaxy
    propagate: 0
  handler_console:
    class: StreamHandler
    args: (sys.stderr,)
    level: INFO
    formatter: generic
  handler_file:
    class: FileHandler
    args: ('{{galaxy_home}}/logs/galaxy.log', 'a')
    formatter: generic
    level: INFO
  formatter_generic:
    format: "%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s"
